import * as Joi from '@hapi/joi';

export const configVaidationSchema = Joi.object({
  DB_HOST: Joi.string().required(),
  DB_PORT: Joi.number().default(5432).required(),
  DB_USERNAME: Joi.string().required(),
  DB_PASSWORD: Joi.string().required(),
  DB_DATABASE: Joi.string().required(),
  PORT: Joi.number().default(4000).required(),
  ACCESS_TOKEN_SECRET: Joi.string().required(),
  ACCESS_TOKEN_EXPIRY: Joi.string().required(),
  REFRESH_TOKEN_SECRET: Joi.string().required(),
  REFRESH_TOKEN_EXPIRY: Joi.string().required(),
  SET_PASSWORD_TOKEN_EXPIRY: Joi.string().required(),
  RESET_PASSWORD_TOKEN_EXPIRY: Joi.string().required(),
  SALT: Joi.number().required(),
  MAIL_HOST: Joi.string().required(),
  MAIL_USER: Joi.string().required(),
  MAIL_PASSWORD: Joi.string().required(),
  MAIL_FROM: Joi.string().required(),
  FE_BASE_URL: Joi.required(),
  CACHE_TTL: Joi.number().required(),
  ADMIN_ID: Joi.required(),
  CRON_T_CHECK_NEW_JOBS: Joi.string().required(),
  CRON_T_GENERATE_REPORT: Joi.string().required(),
  CRON_T_NORMALIZE: Joi.string().required(),
  API_VERSIONING_TYPE: Joi.string().required(),
  API_VERSIONING_HEADER: Joi.string().required(),
  API_VERSION: Joi.string().required(),
});
